# Quantumult X 原版签到配置
# 包含：小蚕霸王餐、晓晓优选、歪麦霸王餐

[general]
dns_exclusion_list = *.cmpassport.com, *.jegotrip.com.cn, *.icitymobile.mobi, id6.me

[dns]
no-ipv6
server = 223.5.5.5
server = 114.114.114.114
server = 119.29.29.29
server = 8.8.8.8

[policy]

[server_remote]

[filter_remote]
FILTER_REGION, tag=CN, force-policy=direct, inserted-resource=true, enabled=true
FILTER_LAN, tag=LAN, force-policy=direct, inserted-resource=true, enabled=true

[rewrite_remote]

[server_local]

[filter_local]
final, direct

[rewrite_local]
# 小蚕霸王餐
^https:\/\/gw\.xiaocantech\.com\/rpc url script-response-body https://gist.githubusercontent.com/Sliverkiss/250a02315f0a2c99f42da3b3573375c8/raw/xcbwc.js

# 晓晓优选
^https:\/\/xxyx-client-api\.xiaoxiaoyouxuan\.com\/my url script-response-body https://gist.githubusercontent.com/Sliverkiss/991a81be1fc8cf2a1937432be68f5521/raw/xxyx.js

# 歪麦霸王餐
^https:\/\/wmapp-api\.waimaimingtang\.com\/api\/api\/v2\/user\/api_user_info_one url script-request-body https://gist.githubusercontent.com/Sliverkiss/49a9ffb2169a2becc33bf4fdbf6eb99a/raw/wmbwc.js

[task_local]
0 9 * * * https://gist.githubusercontent.com/Sliverkiss/250a02315f0a2c99f42da3b3573375c8/raw/xcbwc.js, tag=小蚕霸王餐-定时签到, enabled=true
0 8 * * * https://gist.githubusercontent.com/Sliverkiss/991a81be1fc8cf2a1937432be68f5521/raw/xxyx.js, tag=晓晓优选-定时签到, enabled=true
30 8 * * * https://gist.githubusercontent.com/Sliverkiss/49a9ffb2169a2becc33bf4fdbf6eb99a/raw/wmbwc.js, tag=歪麦霸王餐-定时签到, enabled=true

[http_backend]

[mitm]
hostname = gw.xiaocantech.com, xxyx-client-api.xiaoxiaoyouxuan.com, wmapp-api.waimaimingtang.com
